import test from 'node:test'
import { strict as assert } from 'node:assert'
import { ENTERPRISE_TOOL_NAMES } from '../src/capabilities/tools.js'
import { safeFormula } from '../src/capabilities/guards.js'
import { WorkspaceBoundary } from '../src/workspace/boundary.js'
import { link, mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
test('authority roster and formula boundary fail closed',()=>{assert.deepEqual(ENTERPRISE_TOOL_NAMES,['workspace_list_files','workspace_read_text','spreadsheet_read','spreadsheet_create_output','spreadsheet_update']);for(const bad of ['=WEBSERVICE("x")','=A1!B2','=SUM([x]A1)','=cmd|x'])assert.throws(()=>safeFormula(bad));assert.equal(safeFormula('=SUM(A1:A3)'),'=SUM(A1:A3)')})
test('resource boundary rejects traversal absolute and NUL',async()=>{const b=new WorkspaceBoundary(process.cwd());for(const p of ['../x','C:\\x','a\0b'])await assert.rejects(b.readFileBytes(p))})
test('output-only boundary rejects non-output and overwrite false',async()=>{const root=await mkdtemp(join(tmpdir(),'misen-boundary-'));try{await mkdir(join(root,'output'));await writeFile(join(root,'input.xlsx'),'a');const b=new WorkspaceBoundary(root);await assert.rejects(b.writeOutputFileBytes('input.xlsx',Buffer.from('x')));await b.writeOutputFileBytes('output/a.xlsx',Buffer.from('one'));await assert.rejects(b.writeOutputFileBytes('output/a.xlsx',Buffer.from('two')))}finally{await rm(root,{recursive:true,force:true})}})
test('symlink is rejected or explicitly skipped when Windows denies creation',async t=>{const root=await mkdtemp(join(tmpdir(),'misen-link-'));try{await writeFile(join(root,'x.txt'),'x');try{await symlink(join(root,'x.txt'),join(root,'link.txt'))}catch(e){if((e as NodeJS.ErrnoException).code==='EPERM'){t.skip('Windows EPERM: symlink fixture unavailable');return}throw e}await assert.rejects(new WorkspaceBoundary(root).readFileBytes('link.txt'))}finally{await rm(root,{recursive:true,force:true})}})
test('output reads reject an intra-workspace junction outside the output scope',async t=>{const root=await mkdtemp(join(tmpdir(),'misen-output-scope-'));try{await mkdir(join(root,'private'));await writeFile(join(root,'private','hidden.xlsx'),'hidden');try{await symlink(join(root,'private'),join(root,'output'),'junction')}catch(e){if((e as NodeJS.ErrnoException).code==='EPERM'){t.skip('Windows EPERM: junction fixture unavailable');return}throw e}await assert.rejects(new WorkspaceBoundary(root).readOutputFileBytes('output/hidden.xlsx'),/output|symlink/u)}finally{await rm(root,{recursive:true,force:true})}})
test('secret sentinel and high impact tools are absent',()=>{const source=JSON.stringify(ENTERPRISE_TOOL_NAMES);assert.ok(!source.includes('SENTINEL_SECRET'));for(const forbidden of ['shell','bash','network','web','mcp','subagent','plugin','delete'])assert.ok(!ENTERPRISE_TOOL_NAMES.includes(forbidden as any))})
test('hardlink is rejected or explicitly skipped',async t=>{const root=await mkdtemp(join(tmpdir(),'misen-hardlink-'));try{await writeFile(join(root,'x.txt'),'x');try{await link(join(root,'x.txt'),join(root,'hard.txt'))}catch(e){const code=(e as NodeJS.ErrnoException).code;if(code==='EPERM'||code==='EACCES'){t.skip(`hardlink unavailable: ${code}`);return}throw e}await assert.rejects(new WorkspaceBoundary(root).readFileBytes('hard.txt'))}finally{await rm(root,{recursive:true,force:true})}})
test('injected atomic replacement failure preserves prior output',async()=>{const root=await mkdtemp(join(tmpdir(),'misen-rename-'));class Fail extends WorkspaceBoundary{protected override async commitTemporaryFile():Promise<void>{throw new Error('injected rename failure')}}try{await mkdir(join(root,'output'));await writeFile(join(root,'output','old.xlsx'),'old');const old=await readFile(join(root,'output','old.xlsx'));await assert.rejects(new Fail(root).writeOutputFileBytes('output/old.xlsx',Buffer.from('new'),true));assert.deepEqual(await readFile(join(root,'output','old.xlsx')),old)}finally{await rm(root,{recursive:true,force:true})}})
