import test from 'node:test'
import { strict as assert } from 'node:assert'
import { ENTERPRISE_TOOL_NAMES } from '../src/capabilities/tools.js'
import { safeFormula } from '../src/capabilities/guards.js'
import { WorkspaceBoundary } from '../src/workspace/boundary.js'
import { link, mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
test('authority roster and formula boundary fail closed',()=>{assert.deepEqual(ENTERPRISE_TOOL_NAMES,['workspace_list_files','workspace_read_text','spreadsheet_read','spreadsheet_create_output','spreadsheet_update','document_read','document_create_output','document_update','presentation_read','presentation_create_output','presentation_update']);for(const bad of ['=WEBSERVICE("x")','=HYPERLINK("https://example.com")','=INDIRECT("A1")','=_xlfn.WEBSERVICE("x")','=SUM([Book.xlsx]Sheet1!A1)',"='[Book.xlsx]Sheet1'!A1",'=cmd|x','="a"&"https://x"','=CALL("kernel32")','=RTD("p",,"t")'])assert.throws(()=>safeFormula(bad),bad);for(const good of ['=SUM(A1:A3)','=SUMIFS(Data!C:C,Data!A:A,"Alpha",Data!B:B,">=2026-08-01")','=IFERROR(XLOOKUP($A2,Master!$A:$A,Master!$D:$D),0)','=INDEX(B:B,MATCH("Beta",A:A,0))',"=SUM('7月'!B2:B10)",'=EOMONTH(TODAY(),0)','=TEXT(B2,"#,##0")','=_xlfn.XLOOKUP(A1,B:B,C:C)','=ROUND(売上合計/12,0)','=IF(AND(B2>0,C2<>""),B2*1.1,0)','={1,2,3}'])assert.equal(safeFormula(good),good,good)})
test('resource boundary rejects traversal absolute and NUL',async()=>{const b=new WorkspaceBoundary(process.cwd());for(const p of ['../x','C:\\x','a\0b'])await assert.rejects(b.readFileBytes(p))})
test('output-only boundary allows supported Office types and rejects non-output, unsupported extension, and overwrite false',async()=>{const root=await mkdtemp(join(tmpdir(),'misen-boundary-'));try{await mkdir(join(root,'output'));await writeFile(join(root,'input.xlsx'),'a');const b=new WorkspaceBoundary(root);await assert.rejects(b.writeOutputFileBytes('input.xlsx',Buffer.from('x')));await assert.rejects(b.writeOutputFileBytes('output/a.txt',Buffer.from('x')));for(const extension of ['xlsx','docx','pptx'])await b.writeOutputFileBytes(`output/a.${extension}`,Buffer.from(extension));await assert.rejects(b.writeOutputFileBytes('output/a.xlsx',Buffer.from('two')))}finally{await rm(root,{recursive:true,force:true})}})
test('symlink is rejected or explicitly skipped when Windows denies creation',async t=>{const root=await mkdtemp(join(tmpdir(),'misen-link-'));try{await writeFile(join(root,'x.txt'),'x');try{await symlink(join(root,'x.txt'),join(root,'link.txt'))}catch(e){if((e as NodeJS.ErrnoException).code==='EPERM'){t.skip('Windows EPERM: symlink fixture unavailable');return}throw e}await assert.rejects(new WorkspaceBoundary(root).readFileBytes('link.txt'))}finally{await rm(root,{recursive:true,force:true})}})
test('output reads reject an intra-workspace junction outside the output scope',async t=>{const root=await mkdtemp(join(tmpdir(),'misen-output-scope-'));try{await mkdir(join(root,'private'));await writeFile(join(root,'private','hidden.xlsx'),'hidden');try{await symlink(join(root,'private'),join(root,'output'),'junction')}catch(e){if((e as NodeJS.ErrnoException).code==='EPERM'){t.skip('Windows EPERM: junction fixture unavailable');return}throw e}await assert.rejects(new WorkspaceBoundary(root).readOutputFileBytes('output/hidden.xlsx'),/output|symlink/u)}finally{await rm(root,{recursive:true,force:true})}})
test('secret sentinel and high impact tools are absent',()=>{const source=JSON.stringify(ENTERPRISE_TOOL_NAMES);assert.ok(!source.includes('SENTINEL_SECRET'));for(const forbidden of ['shell','bash','network','web','mcp','subagent','plugin','delete'])assert.ok(!ENTERPRISE_TOOL_NAMES.includes(forbidden as any))})
test('hardlink is rejected or explicitly skipped',async t=>{const root=await mkdtemp(join(tmpdir(),'misen-hardlink-'));try{await writeFile(join(root,'x.txt'),'x');try{await link(join(root,'x.txt'),join(root,'hard.txt'))}catch(e){const code=(e as NodeJS.ErrnoException).code;if(code==='EPERM'||code==='EACCES'){t.skip(`hardlink unavailable: ${code}`);return}throw e}await assert.rejects(new WorkspaceBoundary(root).readFileBytes('hard.txt'))}finally{await rm(root,{recursive:true,force:true})}})
test('injected atomic replacement failure preserves prior output',async()=>{const root=await mkdtemp(join(tmpdir(),'misen-rename-'));class Fail extends WorkspaceBoundary{protected override async commitTemporaryFile():Promise<void>{throw new Error('injected rename failure')}}try{await mkdir(join(root,'output'));await writeFile(join(root,'output','old.xlsx'),'old');const old=await readFile(join(root,'output','old.xlsx'));await assert.rejects(new Fail(root).writeOutputFileBytes('output/old.xlsx',Buffer.from('new'),true));assert.deepEqual(await readFile(join(root,'output','old.xlsx')),old)}finally{await rm(root,{recursive:true,force:true})}})
