import { createHash } from 'node:crypto'
import { readFile, readdir } from 'node:fs/promises'
import { join } from 'node:path'
import { getFormulaText, isFormulaValue } from '@office-kit/xlsx/cell'
import { getCellByCoord } from '@office-kit/xlsx/worksheet'
import { getColumnDimension, getRowDimension } from '@office-kit/xlsx/worksheet'
import { SYNTHETIC_TARGETS, type MonthFixture } from '../../demo/enterprise-excel/fixtures.js'
import { listWorksheetTitles, openSpreadsheetBytes, readCell, readCellStyle, requireWorksheet } from '../spreadsheet/engine.js'
const digest=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex')
export interface ReportingPeriod { readonly year:number; readonly month:number }
export function parseReportPeriod(value:unknown, source:ReportingPeriod){if(typeof value!=='string'||value.length===0)throw new Error('empty report period');if(value===`${source.month}月`||value===`${source.year}年${source.month}月`)return source;throw new Error('report MONTH mismatch')}
export function deriveSourcePeriod(values:readonly unknown[]):ReportingPeriod{if(values.length!==3)throw new Error('exactly three source periods required');const periods=values.map(value=>{if(!(value instanceof Date)||Number.isNaN(value.getTime()))throw new Error('unparseable source As-of');return {year:value.getUTCFullYear(),month:value.getUTCMonth()+1}});const first=periods[0]!;if(periods.some(x=>x.year!==first.year||x.month!==first.month))throw new Error('source reporting periods differ');return first}
function same(a:unknown,b:unknown,label:string){if(JSON.stringify(a)!==JSON.stringify(b))throw new Error(label)}
export type OutputScopeSnapshot = ReadonlyMap<string,string>
/** Capture the authorized output scope before a run so only new artifacts are graded. */
export async function snapshotOutputScope(root:string):Promise<OutputScopeSnapshot>{const entries=await readdir(join(root,'output'),{withFileTypes:true});const snapshot=new Map<string,string>();for(const entry of entries){if(!entry.isFile())throw new Error('output scope contains a non-file entry');snapshot.set(entry.name,digest(await readFile(join(root,'output',entry.name))))}return snapshot}
/** Independent workbook/business validator; it does not use Agent transcript state. */
export async function validateReport(root:string, scenario:MonthFixture, before:ReadonlyMap<string,string>, outputBefore:OutputScopeSnapshot){const sources=scenario.companies.map(x=>`${scenario.month}/${x.company}.xlsx`);const dates=[] as unknown[];for(const file of sources){const w=await openSpreadsheetBytes(await readFile(join(root,file)));dates.push(readCell(w,'Actuals','B4'))}const p=deriveSourcePeriod(dates);for(const [file,hash] of before)if(digest(await readFile(join(root,file)))!==hash)throw new Error(`input hash changed: ${file}`);const outputAfter=await snapshotOutputScope(root);for(const [name,hash] of outputBefore)if(outputAfter.get(name)!==hash)throw new Error(`pre-existing output changed: ${name}`);const created=[...outputAfter.keys()].filter(name=>!outputBefore.has(name));if(created.length!==1)throw new Error('new output count');const name=created[0]!;if(!/\.xlsx$/iu.test(name))throw new Error('new output is not xlsx');const output=`output/${name}`;const w=await openSpreadsheetBytes(await readFile(join(root,output)));if(JSON.stringify(listWorksheetTitles(w))!==JSON.stringify(['Report']))throw new Error('sheet roster');const ws=requireWorksheet(w,'Report');parseReportPeriod(readCell(w,'Report','B2'),p);const expected=scenario.companies;for(let i=0;i<expected.length;i++){const row=i+5,e=expected[i]!;same(readCell(w,'Report',`A${row}`),e.company,'company association');same(readCell(w,'Report',`B${row}`),e.revenue,'revenue association');same(readCell(w,'Report',`C${row}`),e.cost,'cost association');const f=getCellByCoord(ws,`D${row}`);if(!f||!isFormulaValue(f.value)||getFormulaText(f)!==`=B${row}-C${row}`)throw new Error('profit formula');same(readCell(w,'Report',`E${row}`),e.revenue-e.cost>=SYNTHETIC_TARGETS[e.company]?'On target':'Review','status')}
for(const [c,formula] of Object.entries({B:'=SUM(B5:B7)',C:'=SUM(C5:C7)',D:'=SUM(D5:D7)'})){const cell=getCellByCoord(ws,`${c}9`);if(!cell||!isFormulaValue(cell.value)||getFormulaText(cell)!==formula)throw new Error('total formula')}same(readCell(w,'Report','A11'),'Template footer — untouched by the agent','footer');for(const cell of ['A1','A4','B4','A5','B5','E9']){const style=readCellStyle(w,'Report',cell);if(!style||style.font.name!=='Aptos'||style.alignment.vertical!=='center'||!style.numberFormat)throw new Error(`format ${cell}`)}if(getRowDimension(ws,1)?.height!==28||getRowDimension(ws,4)?.height!==22)throw new Error('row height');for(let c=1;c<=5;c++)if(getColumnDimension(ws,c)?.width!==([18,14,14,14,14][c-1]))throw new Error('column width');return {period:p,output}}
