import { Type, type Static } from '@earendil-works/pi-ai'
import type { AgentTool } from '@earendil-works/pi-agent-core'
import { WorkspaceBoundary } from '../workspace/boundary.js'
import { formula, openSpreadsheetBytes, put, serializeSpreadsheet, titles, values } from '../spreadsheet/engine.js'
import { safeFormula, validateDeliverable } from './guards.js'
import { rangeBoundaries, tupleToCoordinate } from '@office-kit/xlsx/utils'

const result = (details: object) => ({ content: [{ type: 'text' as const, text: JSON.stringify(details) }], details })
const Path = Type.Object({ path: Type.Optional(Type.String()), extension: Type.Optional(Type.String()) })
const Text = Type.Object({ path: Type.String(), offset: Type.Optional(Type.Integer({ minimum: 0 })), limit: Type.Optional(Type.Integer({ minimum: 0, maximum: 200000 })) })
const Read = Type.Object({ workbook: Type.String(), sheet: Type.Optional(Type.String()), range: Type.Optional(Type.String()) })
const Create = Type.Object({ source: Type.String(), output: Type.String(), overwrite: Type.Optional(Type.Boolean()) })
const FormulaValue = Type.Object({ formula: Type.String({ minLength: 1, maxLength: 8192 }) }, { additionalProperties: false })
const LiteralValue = Type.Union([Type.String(), Type.Number(), Type.Boolean(), Type.Null()])
const CellValue = Type.Union([LiteralValue, FormulaValue])
const Update = Type.Object({ workbook: Type.String(), sheet: Type.String(), range: Type.String(), values: Type.Array(Type.Array(CellValue)) })
function isFormulaValue(value:unknown):value is {formula:string}{return typeof value==='object'&&value!==null&&!Array.isArray(value)&&Object.keys(value).length===1&&typeof (value as {formula?:unknown}).formula==='string'}
function validateCellValue(value:unknown):void{if(value===null||typeof value==='string'||typeof value==='boolean'||(typeof value==='number'&&Number.isFinite(value)))return;if(isFormulaValue(value)&&value.formula.length>0&&value.formula.length<=8192)return;throw new Error('cell value must be a literal or {formula:string}; cachedValue is not allowed')}
function tool<P>(name: string, description: string, parameters: any, execute: (params: P) => Promise<object>): AgentTool<any> { return { name, label: name, description, parameters, executionMode: 'sequential', execute: async (_id, params) => result(await execute(params as P)) } }
export function enterpriseTools(boundary: WorkspaceBoundary): AgentTool[] {
  return [
    tool<Static<typeof Path>>('workspace_list_files', 'List regular files below the selected workspace.', Path, async p => { const files = await boundary.listFiles(p.path); if (files.length > 20000) throw new RangeError('file listing exceeds 20000 entries'); return { files: p.extension ? files.filter(x => x.toLowerCase().endsWith(p.extension!.toLowerCase())) : files } }),
    tool<Static<typeof Text>>('workspace_read_text', 'Read a UTF-8 workspace text file.', Text, async p => { const r = await boundary.readFileBytes(p.path); if (!/\.(txt|md|markdown|json|csv|yaml|yml|log)$/iu.test(r.absolute)) throw new Error('unsupported text extension'); const all = Buffer.from(r.bytes).toString('utf8'); const offset = p.offset ?? 0; const text = all.slice(offset, offset + Math.min(p.limit ?? 200000,200000)); return { path: boundary.displayPath(r.absolute), text, truncated: offset + text.length < all.length } }),
    tool<Static<typeof Read>>('spreadsheet_read', 'Read workbook sheets or a rectangular range.', Read, async p => { const r = await boundary.readFileBytes(p.workbook); const w = await openSpreadsheetBytes(r.bytes); return p.sheet ? { workbook: boundary.displayPath(r.absolute), sheets: titles(w), sheet: p.sheet, range: p.range ?? 'A1:E20', values: values(w, p.sheet, p.range ?? 'A1:E20') } : { workbook: boundary.displayPath(r.absolute), sheets: titles(w) } }),
    tool<Static<typeof Create>>('spreadsheet_create_output', 'Copy an xlsx template to output.', Create, async p => { const r = await boundary.readFileBytes(p.source); const w = await openSpreadsheetBytes(r.bytes); validateDeliverable(w); const bytes = await serializeSpreadsheet(w); const output = await boundary.writeOutputFileBytes(p.output, bytes, p.overwrite === true); return { source: boundary.displayPath(r.absolute), output: boundary.displayPath(output), bytes: bytes.byteLength } }),
    tool<Static<typeof Update>>('spreadsheet_update', 'Update literal cell values or safe formulas in an output workbook. Use {"formula":"=..."} for formulas. A plain string beginning with "=" remains a literal string.', Update, async p => { if(p.values.length===0||p.values.some(r=>r.length!==p.values[0]!.length)||p.values.length*p.values[0]!.length>10000)throw new Error('values must be a bounded rectangular matrix');for(const row of p.values)for(const value of row)validateCellValue(value); const bounds=rangeBoundaries(p.range); const rows=bounds.maxRow-bounds.minRow+1,cols=bounds.maxCol-bounds.minCol+1;if(rows!==p.values.length||cols!==p.values[0]!.length)throw new Error('values dimensions must exactly match range'); const r = await boundary.readOutputFileBytes(p.workbook); const w = await openSpreadsheetBytes(r.bytes); validateDeliverable(w); const matrix = p.values.map(row => row.map(v => isFormulaValue(v) ? null : v)); put(w, p.sheet, p.range, matrix); for (let y=0;y<p.values.length;y++) for (let x=0;x<p.values[y]!.length;x++) { const v=p.values[y]![x]; if (isFormulaValue(v)) formula(w,p.sheet,tupleToCoordinate(bounds.minCol+x,bounds.minRow+y),safeFormula(v.formula)) } validateDeliverable(w); const bytes=await serializeSpreadsheet(w); await boundary.writeOutputFileBytes(p.workbook,bytes,true); return { workbook: boundary.displayPath(r.absolute), range:p.range, bytes:bytes.byteLength } })
  ]
}
export const ENTERPRISE_TOOL_NAMES = ['workspace_list_files','workspace_read_text','spreadsheet_read','spreadsheet_create_output','spreadsheet_update'] as const
