import { mkdtemp, readFile, readdir, stat, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { performance } from 'node:perf_hooks'
import { fixture, PROMPTS } from '../demo/enterprise-excel/fixtures.js'
import { liveAgent } from '../src/runtime/live.js'
import { snapshotOutputScope, validateReport } from '../src/acceptance/validator.js'
import { createHash } from 'node:crypto'
import { openSpreadsheetBytes, readRange } from '../src/spreadsheet/engine.js'
const arg=process.argv[2]??'july'; const month=arg==='august'||arg==='8月'?'8月':arg==='july'||arg==='7月'?'7月':undefined;if(!month)throw new Error('usage: npm run live -- july|august|7月|8月')
const root=await mkdtemp(join(tmpdir(),'misen-pi-live-')); try { await fixture(root); const scenario=(await import('../demo/enterprise-excel/fixtures.js')).SYNTHETIC_MONTHS.find(x=>x.month===month)!; const hash=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');const before=new Map(await Promise.all(['master.xlsx','月次管理レポート_template.xlsx',...scenario.companies.map(x=>`${month}/${x.company}.xlsx`)].map(async p=>[p,hash(await readFile(join(root,p)))] as const)));const outputBefore=await snapshotOutputScope(root);const started=performance.now(); const agent=liveAgent(root); const starts:string[]=[];const ends:string[]=[];const updateEvidence:Array<{id:string;workbook?:unknown;sheet?:unknown;range?:unknown;values?:unknown;status?:string}>=[]; agent.subscribe(e=>{if(e.type==='tool_execution_start'){starts.push(e.toolName);if(e.toolName==='spreadsheet_update'){const args=e.args as Record<string,unknown>;updateEvidence.push({id:e.toolCallId,workbook:args.workbook,sheet:args.sheet,range:args.range,values:args.values,status:'started'})}}if(e.type==='tool_execution_end'){ends.push(e.toolName);const evidence=updateEvidence.find(item=>item.id===e.toolCallId);if(evidence)evidence.status=e.isError?'error':'success'}}); await agent.prompt(PROMPTS[month]);if(agent.state.errorMessage)throw new Error('provider or tool failure');let result;try{result=await validateReport(root,scenario,before,outputBefore)}catch(error){const outputs=(await readdir(join(root,'output')));let reportCells:unknown=undefined;const xlsx=outputs.filter(name=>name.toLowerCase().endsWith('.xlsx'));if(xlsx.length===1){try{const workbook=await openSpreadsheetBytes(await readFile(join(root,'output',xlsx[0]!)));reportCells={A1_B2:readRange(workbook,'Report','A1:B2'),A5_C7:readRange(workbook,'Report','A5:C7')}}catch{reportCells='unavailable'}}console.error(JSON.stringify({month,status:'FAIL',failure:error instanceof Error?error.message:'validation failure',outputs,reportCells,spreadsheetUpdates:updateEvidence,toolStarts:starts,toolEnds:ends,toolBalance:starts.length===ends.length}));throw error}const bytes=(await stat(join(root,result.output))).size;console.log(JSON.stringify({month,status:'PASS',validation:['SHEET','MONTH','ROWS','PROFIT_FORMULAS','STATUS','TOTAL','FOOTER','FORMAT','new-output-count','input-hashes'],output:{path:result.output,bytes},spreadsheetUpdates:updateEvidence,toolStarts:starts,toolEnds:ends,toolBalance:starts.length===ends.length,elapsedMs:Math.round(performance.now()-started),rss:process.memoryUsage().rss})) } finally { await rm(root,{recursive:true,force:true}) }
